### ISSUE TITLE
Make database changes a bit more migratable 

### ISSUE THREAD

**Issue by sigismund** [cryptoeax/arbbot#101]
Currently there is no database migration tool and for every change in database there has to be a custom php script with SQL sentences, with which there is always a danger of irreversible changes.

Everything could be simplified by using migration library like [phinx](https://github.com/cakephp/phinx)

**Comment by cryptoeax** [comment]
Thanks, this indeed looks much better than the current hand-rolled solution, I'll try to remember to use it in the future...
