### ISSUE TITLE
Notice: Undefined index: orderid in /var/www/arbbot/bot/BittrexLikeExchange.php on line 353

### ISSUE THREAD

**Issue by heiko7even** [cryptoeax/arbbot#103]
<img width="852" alt="bildschirmfoto 2018-01-15 um 19 15 55" src="https://user-images.githubusercontent.com/27195613/34956242-914c7b9a-fa28-11e7-9342-ee3db7e6a467.png">

**Comment by andygoossens** [comment]
Duplicate of #92

**Comment by cryptoeax** [comment]
Closing as a duplicate.
