### ISSUE TITLE
Error on Trading

### ISSUE THREAD

**Issue by heiko7even** [cryptoeax/arbbot#108]
Getting those errors on trades.

<img width="1474" alt="bildschirmfoto 2018-01-17 um 15 52 45" src="https://user-images.githubusercontent.com/27195613/35048870-9d10ac2c-fb9e-11e7-9c9b-e82d88ea0e84.png">

<img width="1074" alt="bildschirmfoto 2018-01-17 um 15 53 07" src="https://user-images.githubusercontent.com/27195613/35048871-9d3dea84-fb9e-11e7-97dd-dc9026c95d26.png">

**Comment by cryptoeax** [comment]
Check the log message, it tells you what you should do if this happens regularly!
