### ISSUE TITLE
Not enough coins at top of the orderbook!

### ISSUE THREAD

**Issue by claytondukes** [cryptoeax/arbbot#123]
I probably changed some setting and messed something up, but I'm not sure what. Can someone explain what this means and any recommendations to fix it?

```
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Filling need 117.64539751 XPM @ BLEUTRADE
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Not enough coins at top of the orderbook!
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Rolling the dice...
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Filling need 117.64539751 XPM @ BLEUTRADE
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Not enough coins at top of the orderbook!
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Rolling the dice...
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Filling need 117.64539751 XPM @ BLEUTRADE
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Not enough coins at top of the orderbook!
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Rolling the dice...
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Filling need 117.64539751 XPM @ BLEUTRADE
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Not enough coins at top of the orderbook!
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Rolling the dice...
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Filling need 117.64539751 XPM @ BLEUTRADE
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Not enough coins at top of the orderbook!
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Rolling the dice...
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Filling need 117.64539751 XPM @ BLEUTRADE
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Not enough coins at top of the orderbook!
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Rolling the dice...
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Filling need 117.64539751 XPM @ BLEUTRADE
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Not enough coins at top of the orderbook!
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Rolling the dice...
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Filling need 117.64539751 XPM @ BLEUTRADE
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Not enough coins at top of the orderbook!
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Rolling the dice...
Jan 24 07:50:31 cb arbbot[1287]: 07:50:31: Filling need 117.64539751 XPM @ BLEUTRADE
Jan 24 07:50:32 cb arbbot[1287]: 07:50:32: Not enough coins at top of the orderbook!
Jan 24 07:50:32 cb arbbot[1287]: 07:50:32: Rolling the dice...
Jan 24 07:50:32 cb arbbot[1287]: 07:50:32: Filling need 11.53796015 NMC @ BLEUTRADE
Jan 24 07:50:32 cb arbbot[1287]: 07:50:32: Posting buy order to BLEUTRADE: 11.53796015 NMC for 0.00414894 @ 0.00035959
```

**Comment by cryptoeax** [comment]
I don't see anything wrong, the orderbook is too thin, the bot can't do anything about that.

BTW Github issues is the wrong place to ask questions.  Please let's keep Github focused on development issues, thanks.

**Comment by claytondukes** [comment]
I think this is maybe a documentation issue - I'm not clear on what an "orderbook" refers to here and why it would cause this or how to fix it.
Is it a config setting? some ratio thing? some autobuy thing? etc. I did try searching prior tickets but didn't see anything. So no documentation, no tickets, kinda hard to know :)

FWIW, I'd be happy to contribute the documentation on it if I knew - just don't know. 
(I realize how much work you put in, so I'm not complaining, just want to understand so I can help where possible)

**Comment by cryptoeax** [comment]
> I think this is maybe a documentation issue - I'm not clear on what an "orderbook" refers to here and why it would cause this or how to fix it.

Yes, it is a documentation issue for sure!

> Is it a config setting? some ratio thing? some autobuy thing? etc. I did try searching prior tickets but didn't see anything. So no documentation, no tickets, kinda hard to know :)

Orderbook is a common trading term, see https://www.investopedia.com/terms/o/order-book.asp.  FWIW the bot is full of trading jargon, which may be unfamiliar to some.

> FWIW, I'd be happy to contribute the documentation on it if I knew - just don't know.
> (I realize how much work you put in, so I'm not complaining, just want to understand so I can help where possible)

Yes, I understand and appreciate the offer to help.  :-)

I started a wiki page to help document the jargon used in arbbot, help for filling it up is appreciated: https://github.com/cryptoeax/arbbot/wiki/Jargon.  I think you should be able to create other wiki pages yourself (if not feel free to ping me and I'll create them for you) so I appreciate any help with writing documentations in the form of the wikis for the project.  The good thing about using wikis is that you don't need to worry too much about the formatting or structure as they all can be changed/fixed after the fact.  :-)

(BTW sorry the documentation on this project has been so thin so far...  As you can see I have had to devote my time mostly to coding activities so far)
