### ISSUE TITLE
Error orderbooks

### ISSUE THREAD

**Issue by OlegVic** [cryptoeax/arbbot#127]
`  private function testOrderbooks( $o1, $o2 ) {
    if ( is_null( $o1 ) ) {
      logg( sprintf( "Received invalid orderbook received from %s. Skipping...",
                     $o1->getSource()->getName() ) );
      return false;
    }
    if ( is_null( $o2 ) ) {
      logg( sprintf( "Received invalid orderbook received from %s. Skipping...",
                     $o2->getSource()->getName() ) );
      return false;
    }
    return $this->checkAndTrade( $o1, $o2 );
  }
`
If `$o1` is NULL what this code `$o1->getSource()->getName()` can return?

**Comment by ericfraselle** [comment]
An error, if we want the name of the exchange, we have to add $x1 and $x2 as parameters

**Comment by cryptoeax** [comment]
Oops, I had another version of this on the binance branch, and I ended up cherry-picking the wrong commit to the production branch...  I'll fix this.

**Comment by cryptoeax** [comment]
e161fbbe646a5aa51f73feb58a31237e6dee3b63 is the right commit, pushed to production!
