### ISSUE TITLE
Docker Issue for new setup

### ISSUE THREAD

**Issue by jjc6676** [cryptoeax/arbbot#130]
Running docker-compose build and towards the end I receive this.
Thoughts?

E: Sub-process /usr/bin/dpkg returned an error code (1)
ERROR: Service 'bot' failed to build: The command '/bin/sh -c apt-get install -y     libicu-dev unzip ntpdate libmcrypt-dev zlib1g-dev g++ mysql-client ntp     && rm -r /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by cryptoeax** [comment]
It is hard to say what went wrong.  Can you please post your full log to gist.github.com and include a link to it here?  Thanks!

**Comment by jjc6676** [comment]
Figured this out.
Was necessary to install the latest release of Composer than the current one due to the need of using v3 yml

**Comment by cryptoeax** [comment]
The documentation _does_ say: <quote>Install the latest versions of docker and docker-compose</quote>  :-)
