### ISSUE TITLE
CCXTAdapter should stop uppercasing coin names

### ISSUE THREAD

**Issue by andygoossens** [cryptoeax/arbbot#134]
Every ccxt-based exchange needs to stop uppercasing coin names. Calling a ccxt method with an unknown coin (as names are considered case sensitive) will fail.

e.g. HitBtc has the CAT coin, which ccxt translates to "BitClave". So when the CCXTAdapter (or exchange impl) uppercases that to "BITCLAVE" and you call a ccxt method with that, it fails.

**Comment by cryptoeax** [comment]
Not uppercasing the coin names is also not the correct solution since our other exchange backends do that currently.  The correct solution is to translate the coin names to their original names before passing them to ccxt APIs.

**Comment by cryptoeax** [comment]
I think 4f3a3ec7b7ff618a9c3552ac4e3423041bbfbdae is a fix for this.  I pushed it to the binance branch.  It's possible this isn't sufficient but it's hard to test on Binance, so please let me know if you find bugs in it on HitBTC.
