### ISSUE TITLE
Adhere to rounding preferences of each exchange

### ISSUE THREAD

**Issue by andygoossens** [cryptoeax/arbbot#136]
Some exchanges are really picky about the values we are sending them in our requests. They won't accept some quantities, rates or amounts when they were not rounded to X places.

Other exchanges are a bit more lenient and (can) do some rounding for you (e.g. HitBTC when creating an order and strictValidate=false). But that could lead to cases where our buy-factor and sell-factor calculations became useless. e.g.
* rate was 0.00000062
* we apply the buy factor (1.005), so we end up with 0,0000006231
* assuming reduced sell rate is still below buy rate, we will send an order to the exchange
* exchange has a preference for up to 8 decimals for this coin's rate, so it will round the rate back to 0.00000062
* maybe you got lucky and your order got executed, or maybe it should have been raised to 0.00000063 instead?

Note that HitBTC can round your amounts as well (when strictValidate=false). e.g.
* you send an order for 1234 DOGE
* but the exchange expects a multiple of 1000
* the exchange rounds your amount down to 1000
* you end up with an unexpected number of bought/sold coins, which might hurt your profitability
* using strictValidate=true to avoid rounding is not a solution as the order will just fail instead

This is not just an issue with creating orders, it can be an issue for withdrawals as well. e.g. the amount to withdraw can have no more than 8 decimals.

When I look in ccxt classes, I see that some exchange implementations have hard-coded the required precisions, and others retrieve that information from the exchange itself.

**Comment by cryptoeax** [comment]
Everything you said here makes sense to me, except for `strictValidate`.  Not sure what you are referring to there...

**Comment by cryptoeax** [comment]
Fixed in this commit series: https://github.com/cryptoeax/arbbot/compare/884f836...0c82dd3.

**Comment by andygoossens** [comment]
Don't worry about `strictValidate`. That is a HitBTC specific parameter that dictates whether the server should be strict or lenient with amounts/rates in "create order" requests.

**Comment by cryptoeax** [comment]
Alright, makes sense.  Thanks!
