### ISSUE TITLE
Website not fully loading

### ISSUE THREAD

**Issue by dinesh0311** [cryptoeax/arbbot#142]
Hi, 
I am running arbbot in centos 6.9 and using web interface. I am getting the following error message and a incomplete website. If someone can point out what I am doing wrong it will be really helpful. Thanks.

Starting arbbot trader: 08:33:25: ARBITRATOR V2.0 launching...
08:33:25: Loading config...
08:33:25: Enabling Bittrex...
08:33:25: Enabling Bleutrade...
08:33:25: Enabling Poloniex...
08:33:25: Configured 3 exchanges!
08:33:25: Testing exchange access...
08:33:26: [BITTREX] API error response: APIKEY_INVALID
08:33:26: [BITTREX] API error response: APIKEY_INVALID
08:33:26: [BITTREX] API error response: APIKEY_INVALID
08:33:27: [BITTREX] API error response: APIKEY_INVALID
08:33:27: [BITTREX] API error response: APIKEY_INVALID
08:33:27: BITTREX [ERROR]
API error response: APIKEY_INVALID
![error](https://user-images.githubusercontent.com/2213870/35613516-4c977854-0664-11e8-8e7f-a065684ff0b0.png)

**Comment by cryptoeax** [comment]
The log message is explaining what's wrong very clearly.  Please spend more time studying the README and the error messages.
