### ISSUE TITLE
Error in web UI interface

### ISSUE THREAD

**Issue by dinesh0311** [cryptoeax/arbbot#151]
Sorry for the disturbance, but for almost a week I am working in installing the bot but getting some error when accessing web UI. Any help would be helpful, as to just pointing me in a direction where I might be doing wrong would be enough. 

I am getting the below error when I debug the page,

Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.success (ui.js:825)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at A (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)

This is the line I am getting the error,
                Object.keys(btcData).forEach(function(xid) {

**Comment by cryptoeax** [comment]
I think that happens because none of your exchange accounts have a BTC wallet.  This commit should fix the error: 4e954edd0c27992a46c62a5756134c3b960ea8f4
