### ISSUE TITLE
[Bittrex] CURRENCY_OFFLINE

### ISSUE THREAD

**Issue by OlegVic** [cryptoeax/arbbot#152]
13:04:40: [BITTREX] API error response: CURRENCY_OFFLINE
13:04:40: Error during main loop: API error response: CURRENCY_OFFLINE

BittrexLikeExchange.php(61): BittrexLikeExchange->queryDepositAddress('XLM')

https://bittrex.com/api/v1.1/public/getcurrencies => 

{"Currency":"XLM","CurrencyLong":"Lumen","MinConfirmation":2,"TxFee":0.01000000,"IsActive":false,"CoinType":"LUMEN","BaseAddress":"GB6YPGW5JFMMP2QB2USQ33EUWTXVL4ZT5ITUNCY3YKVWOJPP57CANOF3","Notice":"Wallet Disabled - performing routine maintenance"}

**Comment by cryptoeax** [comment]
This is an error from the exchange, there is nothing we can do about it.  4dcc193 detects this situation and makes sure we don't use the altcoin in future loops.
