### ISSUE TITLE
Bot never enters trade. Says below minimum threshold everytime. 

### ISSUE THREAD

**Issue by agencypress** [cryptoeax/arbbot#153]
I have set the bot to use 0.001 Bitcoin as a minimum to enter a trade. The bot is continually finding opportunities but each time it does not enter a trade.

Could it be  too little to trade with according to Bleutrade and Poloniex Policies? 
Or an issue with the App. 

Please help

**Comment by cryptoeax** [comment]
The error messages are clear, the thresholds are coming from exchange minimum trade sizes.

**Comment by agencypress** [comment]
Thank you very much for your reply....

I have been reviewing the minimum thresholds on multiple exchanges for the
past few hours.

I think I may be missing something.
I will look deeper


But thank you
