### ISSUE TITLE
Kraken exchange

### ISSUE THREAD

**Issue by sinaxi** [cryptoeax/arbbot#154]
Is it possible to use Kraken with
- Bleutrade 
- Poloniex

I can't use Bittrex so I'd like to know if is it possible to arbitrage with Kraken

**Comment by cryptoeax** [comment]
AFAIK Kraken doesn't allow you to withdraw without using 2FA, so the bot cannot currently use it.  (This is what other users have told me, I don't use Kraken myself.)

**Comment by andygoossens** [comment]
FYI: It is not possible to withdraw coins through the API unless you already have the destination address in their "address book". At most you can have 50 addresses.

**Comment by sinaxi** [comment]
Thanks for your replies!!
So if I can't use Bittrex, I'll use only:

- Bleutrade
- Poloniex

Is there other exchange that I can use?

Thanks

**Comment by cryptoeax** [comment]
Not right now.  There is a PR open for HitBTC but I'm not sure about the quality of that backend yet.  Help in adding more is appreciated.

**Comment by cryptoeax** [comment]
Oh BTW I forgot to mention the [Binance branch](https://github.com/cryptoeax/arbbot/tree/binance) that is very close to being merged now, you can switch to using that branch right now.

**Comment by sinaxi** [comment]
What is this "Binance branch"? Can you tell me differences between this link and original https://github.com/cryptoeax/arbbot
