### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by born2hate** [cryptoeax/arbbot#16]
POLONIEX [ERROR]
[POLONIEX] API error response: Invalid nonce parameter.

What is this? please assist

**Comment by cryptoeax** [comment]
We're discussing this in #15.  It seems that new users are getting this error and I'm trying to figure out why.

Do you mind running this command in your installation directory and pasting the result here so that I can see the exact version you are running please? `git rev-parse HEAD`

Thanks!

**Comment by born2hate** [comment]
b0a4cea8db80404031e8270f9f2969ae791da44c

**Comment by born2hate** [comment]
installed scp on ubuntu, its all ok :)

**Comment by cryptoeax** [comment]
I'm going to close this issue since the other one is already covering this bug...
