### ISSUE TITLE
Webinterface problem

### ISSUE THREAD

**Issue by kingchenx** [cryptoeax/arbbot#19]
hi,
i have some problems with the webinterface^^ because i get this error after i logged in with my correct username and password, that i created with htpasswd... 
500 Internal Server Error
nginx/1.10.3 (Ubuntu)
thx :)

**Comment by remipaeta** [comment]
Use this command:
sudo chown -R www-data:www-data /var/www/'yourdirectory"

**Comment by remipaeta** [comment]
Use it without " " of course ^^

**Comment by kingchenx** [comment]
Mhmm, this works not for me, get the same error :/

**Comment by remipaeta** [comment]
Ok try this:
chmod 754 -R /var/www/yourdirectory

**Comment by kingchenx** [comment]
Nope, still not work :/

**Comment by born2hate** [comment]
the simplest way is to install vestacp nginx+php-fpm on fresh version of server.
works for me :)

**Comment by cryptoeax** [comment]
I suggest looking at the error logs for your web server, this error message is very generic and it basically means "something went wrong" so it's hard to say more without knowing the specifics.

For example if you are using nginx on Ubuntu, the following command should reveal the issue if you run it right after the error 500 has shown up in a web browser (you can run the `date` command immediately after it to dump out the current server date to see which lines in the log are current.)

```
sudo tail /var/log/nginx/error.log
```

**Comment by kingchenx** [comment]
this is the error.log

2017/12/13 22:29:01 [error] 15986#15986: *1 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2017/12/13 22:29:01 [error] 15986#15986: *2 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost"
2017/12/13 22:29:01 [error] 15988#15988: *3 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost"

**Comment by cryptoeax** [comment]
Hmm, in your nginx config, if you replace the line that starts with `try_files` with `try_files $uri $uri/ =404;`, does the problem go away?

**Comment by cryptoeax** [comment]
(basically replace `/index.html` there with `=404`)

**Comment by kingchenx** [comment]
with `try_files $uri $uri/ =404;` i get the error -> 404 Not Found

**Comment by kingchenx** [comment]
i dont know what i am doing wrong....

i now replaced `try_files $uri $uri/ =404;` and `try_files $uri $uri/ /index.html;` with `try_files $uri/ $uri /index.php?$query_string;`, and now the `sudo tail /var/log/nginx/error.log` give ->

`try_files $uri/ $uri /index.php?$query_string;` ---->
2017/12/14 00:20:02 [error] 871#871: *1 user "xY": password mismatch, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"

`try_files $uri $uri/ /index.html;` ------>
2017/12/14 00:38:57 [error] 3206#3206: *1 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"

 `try_files $uri $uri/ =404;`------->
2017/12/14 00:38:00 [error] 872#872: *3 user "xY" was not found in "/var/www/conf/arbitrage.passwd", client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"

im just confused, 3 various errors ...  and yes, all Nick/Pass is 100% correct, if i use a wrong password, the page refuse the login, with the *correct logins* the page let me in and give me the erros..

**Comment by cryptoeax** [comment]
What happens if you completely remove the `try_files` lines altogether?  This is something that I have inherited from the original repo and I don't actually understand why it's necessary, now that I am consulting the [documentation](http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files).

The first and last log lines suggest that the user and password you are using  isn't working, can you delete `/var/www/conf/arbitrage.passwd` and try regenerating it again please?

**Comment by kingchenx** [comment]
didnt work to generate a new arbitrage.passwd, and after removing` try_files ....` i get this ->
404 Not Found ----->
2017/12/14 02:02:52 [warn] 2265#2265: conflicting server name "localhost" on 0.0.0.0:80, ignored
2017/12/14 02:02:59 [error] 2268#2268: *1 "/var/www/arbitrage-production/web/index.html" is not found (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"

**Comment by cryptoeax** [comment]
OK there is something completely wrong with your nginx configuration.  Sorry but resolving it is beyond the scope of this project.  :-)  Please ask for help in places like https://serverfault.com/.

But from the errors you're getting, it's clear that:

  * You have another site configured named localhost to run in nginx.
  * The path to where Arbitrator is installed isn't correctly entered in the nginx config.

**Comment by cryptoeax** [comment]
I removed `try_files` from the instructions in 36e6e46.  Closing the issue since the rest of the problems seem to be configuration issues on @kingchenx's side.

**Comment by kingchenx** [comment]
@cryptoeax , what a fail from me :( im sorry for wasting your time...
The path was rly not correct in the nginx, now looks good for me so..
"arbbot-production" - after fresh installation/unzip and not arbitrage-production ;)

> the server {
> 
>         listen 80;
>         root /var/www/arbbot-production/web;
>         index index.html;
>         server_name localhost;
> 
>         location / {
> 
>                 auth_basic           "Restricted area";
>                 auth_basic_user_file /var/www/conf/arbitrage.passwd;
> 
>         }
> 
>         location ~ \.php$ {
> 
>           include snippets/fastcgi-php.conf;
>           fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
> 
>         }
> 
> }

**Comment by cryptoeax** [comment]
Thanks, updated the instructions in 502a739.
