### ISSUE TITLE
poloniex API problem

### ISSUE THREAD

**Issue by alican-soysal** [cryptoeax/arbbot#22]
Hello,

When I try to run main.php, there is an error:

[ERROR] [POLONIEX] API error response: Invalid nonce parameter.

I tried to delete and create new API for three times but nothing is changed.

**Comment by kingchenc** [comment]
https://github.com/cryptoeax/arbbot/issues/16

https://github.com/cryptoeax/arbbot/issues/15

https://github.com/cryptoeax/arbbot/issues/8

**Comment by cryptoeax** [comment]
What version are you running?  If you have cloned from git, can you please run `git rev-parse HEAD`?  Otherwise can you please download the latest ZIP file from the production branch and try running that?

**Comment by cryptoeax** [comment]
This has been fixed on the `production` branch.
