### ISSUE TITLE
Poloniex Invalid data received

### ISSUE THREAD

**Issue by grim888** [cryptoeax/arbbot#24]
22:23:46: [POLONIEX] Invalid data received: ([])
22:23:46: [POLONIEX] Invalid data received: ([])
22:23:46: [POLONIEX] Invalid data received: ([])
22:23:46: [POLONIEX] Invalid data received: ([])
22:23:46: [POLONIEX] Invalid data received: ([])
22:23:46: Error during main loop: [POLONIEX] Invalid data received: ([])

#0 /var/www/arbbot/bot/xchange/Poloniex.php(357): Poloniex->queryAPI('returnDepositAd...')

#1 /var/www/arbbot/bot/xchange/Poloniex.php(238): Poloniex->queryDepositAddresses()

#2 /var/www/arbbot/bot/Arbitrator.php(411): Poloniex->refreshExchangeData()

#3 /var/www/arbbot/bot/Arbitrator.php(38): Arbitrator->refreshCoinPairs()

#4 /var/www/arbbot/bot/Arbitrator.php(436): Arbitrator->loop()

#5 /var/www/arbbot/main.php(71): Arbitrator->run()

#6 {main}

**Comment by cryptoeax** [comment]
I believe 4f71dd405d7a1e64bd44ef9296296d9800a63c8c should fix this.

**Comment by cryptoeax** [comment]
Confirmed by @grim888 on gitter.
