### ISSUE TITLE
'Cloud not get reply HTTP 422'

### ISSUE THREAD

**Issue by andremrtc** [cryptoeax/arbbot#29]
Hello, I'm trying to run your latest 'baaa6ba' version, however I'm getting the HTTP 422 error.

Version downloaded yesterday was connecting with poloniex perfectly, but now it has stopped.

Thank you.

![http422](https://user-images.githubusercontent.com/32331400/34073984-19adae36-e28d-11e7-8110-e2e7c9a7ba3b.png)

**Comment by andremrtc** [comment]
After waiting a few minutes I tried again to run the bot and it worked!

After 15 minutes or so running it looped showing the same error, but with different messages.

![http422 2](https://user-images.githubusercontent.com/32331400/34074391-0906a22e-e295-11e7-9813-1a0535bcda17.png)

**Comment by jjc6676** [comment]
I think the exchanges are bogged down and not something wrong with the bot.

Same with Bittrex

**Comment by andremrtc** [comment]
With you is the same problem ?

**Comment by andremrtc** [comment]
After waiting a few minutes I tried again to run the bot and it worked!

After 15 minutes or so running it looped showing the same error, but with different messages.

![http422 2](https://user-images.githubusercontent.com/32331400/34074429-ee0fb36a-e295-11e7-9b9f-aafd6a3c8789.png)

**Comment by cryptoeax** [comment]
This is an error from the exchange.  Previously the bot had a bug which would mask errors such as this so you wouldn't see them, now the bot will make 5 attempts for each API call to an exchange and will then give up if it still can't make the call successfully.  What you are seeing above is an exchange returning an error for an extended period of time, there is nothing wrong with the bot.
