### ISSUE TITLE
Handle Bittrex minimum tick sizes

### ISSUE THREAD

**Issue by cryptoeax** [cryptoeax/arbbot#36]
Per their Nov 24 email:

*Creating minimum tick sizes*: Within the next 2 weeks, on a per market basis, we will be instituting minimum tick sizes that are based on the current price of the market.  The target is to have minimum trade sizes that are near 0.1% of the current price.  The current minimum tick size is 1 Satoshi.  For example, Ethereum trades at 0.0577 Bitcoin.  Bids and asks can only be placed in 0.0001 increments.  So the next levels allowable levels on the order book will be 0.0576 and 0.0578.

This means that if the bot tries to place any random order it may fail.  It would be nice if someone can let me know if they have seen their bot run into any errors when trading on Bittrex due to this change recently.  Thanks!

**Comment by cryptoeax** [comment]
Looks like #35 has taken care of the issue completely thankfully.

**Comment by cryptoeax** [comment]
Perhaps we need to reopen this, looks like `MIN_TRADE_REQUIREMENT_NOT_MET` errors are back...

**Comment by Exalovic** [comment]
As seen I got this error today
![8wih1yj](https://user-images.githubusercontent.com/34724438/34783727-9c7b9d7a-f62c-11e7-8eb8-1ca69c37a5d6.png)

**Comment by Exalovic** [comment]
Got another one, i have 28 vrc on the exchange and max trade size set to 0.005 so it should be able to do much bigger trades anyways

![vxvbh0b](https://user-images.githubusercontent.com/34724438/34784867-ccf9b650-f62f-11e7-8e11-02ee7c6b4f47.png)

**Comment by cryptoeax** [comment]
This was fixed in 4655aecae18e2197335a1b67b3fd745c41093ea7 and the related commit series.
