### ISSUE TITLE
Add error control for rebalance

### ISSUE THREAD

**Issue by Scorpic1** [cryptoeax/arbbot#4]
After rebalnce on one exchange have error and it moment not control.
![2017-12-05_124649](https://user-images.githubusercontent.com/18716398/33600644-e0f2c908-d9ba-11e7-8030-dc314999dce7.jpg)

**Comment by cryptoeax** [comment]
This should show up in the Alerts section in the UI once the manage cycle has run.  Does it not?  Do you have stuck withdrawal detection enabled in `config.ini`?

**Comment by Scorpic1** [comment]
Better check anyway with rebalnce, if not in alert.

**Comment by cryptoeax** [comment]
That is what I'm trying to say, the rebalancing also happens during the management phase, so if a withdrawal error happens in a given management phase, the next time the stuck withdrawal detection phase runs it will get reported.

The reason the stuck detection phase doesn't run very often is that it is time consuming and running it too often reduces the efficiency of the bot.  But its frequency can be controlled with the `expert.interval-stuck-detection` entry (which is the interval of running this job in hours).

Does this sound like a reasonable solution?

**Comment by jjc6676** [comment]
Can we add another TOTAL BTC to the chart and Wallets section that adds the TOTAL BTC + TOTAL ALTCOINS?



So TOTAL BTC+ALT = XXX

**Comment by cryptoeax** [comment]
> Can we add another TOTAL BTC to the chart and Wallets section that adds the TOTAL BTC + TOTAL ALTCOINS? So TOTAL BTC+ALT = XXX

Yes, that sounds like a good idea, but I appreciate if you can file a separate issue please.  It's hard to keep track of multiple unrelated features per issue.  Thanks.  :-)

**Comment by cryptoeax** [comment]
I think what has been asked for here is covered by the functionality already provided.  If not, please describe why after studying the existing configuration options.
