### ISSUE TITLE
Cannot redeclare doWithdraw()

### ISSUE THREAD

**Issue by cryptoner** [cryptoeax/arbbot#40]
Hello! Thank u for work!
`
07:54:29: Transfering 88.29302848 LBC BITTREX => POLONIEX
PHP Fatal error:  Cannot redeclare doWithdraw() (previously declared in /var/www/arbbot-production/bot/CoinManager.php:761) in /var/www/arbbot-production/bot/CoinManager.php on line 761
`
Branch: pl-rewrite

**Comment by cryptoeax** [comment]
Oops, that's weird, I'll push a fix in a minute.
