### ISSUE TITLE
The bot sometimes ignores the min-profit set in the config

### ISSUE THREAD

**Issue by Exalovic** [cryptoeax/arbbot#43]
![yhmvmes](https://user-images.githubusercontent.com/34724438/34277702-305ebcc4-e6a7-11e7-8921-cbf82e72546c.png)

As seen in the example I have set a min-profit = 0.00001 in the config but the bot still performs the trade even though the simulation gives a potential profit lower than the setting.

I can see from the top line that the initial simulation is above the threshold, but the bot should stop it self when the second simulation returns a lower profit

**Comment by cryptoeax** [comment]
Sorry you are s a bit confused here.

The profit you see on the screen is from a simple trade simulation done for the purpose of logging! https://github.com/cryptoeax/arbbot/blob/936159e293dd8f56529d5a3a0dc44449d2aab277/bot/Arbitrator.php#L256

This is where the bot actually simulates the trade it's about to make.  https://github.com/cryptoeax/arbbot/blob/936159e293dd8f56529d5a3a0dc44449d2aab277/bot/Arbitrator.php#L188  As you can see, the profit amount is checked against the config variable just fine.
