### ISSUE TITLE
Error running bot

### ISSUE THREAD

**Issue by seaspray09** [cryptoeax/arbbot#49]
Hello,

On trying to start the bot, there is an error appearing folllowing restart of the webserver as shown below.  
Please assist in resolving this issue that is appearing upon executing the command  "php main.php".  Thanks.

/var/www/arbbot-production$ /etc/init.d/nginx restart
[ ok ] Restarting nginx (via systemctl): nginx.service.

/var/www/arbbot-production$ php main.php
PHP Warning:  mysqli_connect(): (HY000/1045): Access denied for user 'arbitrage'@'localhost' (using password: YES) in /var/www/arbbot-production/lib/mysql.php on line 66
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to mysql_error() must be an instance of mysqli, boolean given, called in /var/www/arbbot-production/bot/Database.php on line 20 and defined in /var/www/arbbot-production/lib/mysql.php:227
Stack trace:
  /var/www/arbbot-production/bot/Database.php(20): mysql_error(false)
  /var/www/arbbot-production/bot/Database.php(132): Database::connect()
  /var/www/arbbot-production/bot/utils.php(44): Database::log('ARBITRATOR V2.0...')
  /var/www/arbbot-production/main.php(29): logg('ARBITRATOR V2.0...')
  {main}
  thrown in /var/www/arbbot-production/lib/mysql.php on line 227

**Comment by cryptoeax** [comment]
Please follow the installation instructions in the README file.

**Comment by seaspray09** [comment]
When following the instructions in the README file, and installing the required packages using the line

sudo apt-get install php-cli php-curl php-mysqlnd mysql-server nginx-full php-fpm unzip apache2-utils ntpdate

it is giving the following result

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php7.0-mysql' instead of 'php-mysqlnd'

Is it supposed to be installing php7.0-msql in place of php-mysqlnd ? 
Please advise.  Thanks.

**Comment by cryptoeax** [comment]
Yeah, that's fine.  I should probably update that part of the docs...
