### ISSUE TITLE
Add support for Bleutrade

### ISSUE THREAD

**Issue by cryptoeax** [cryptoeax/arbbot#54]
(Blocks #5)

**Comment by cryptoeax** [comment]
Support for Bleutrade is ready for testing on [this branch](https://github.com/cryptoeax/arbbot/tree/bleutrade).  Please use care as there may be bugs in the code still.  I appreciate feedback and bug reports.

**Comment by cryptoeax** [comment]
Note that I have landed quite a few fixes on this branch, and at this point it should be quite stable for testing out.

**Comment by cryptoeax** [comment]
I think Bleutrade is working pretty solidly for me.  @rpcrypto, what do you think?  I'm planning to merge this to production shortly unless if you think there's a big outstanding issue that needs to be fixed before this is ready for general usage.

**Comment by remipaeta** [comment]
Yes you can !! ^^

**Comment by cryptoeax** [comment]
Merged the bleutrade branch to production and deleted this branch since it is now obsolete.  The bleutrade exchange is now ready for general use.
