### ISSUE TITLE
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

### ISSUE THREAD

**Issue by ghost** [cryptoeax/arbbot#59]
now getting this error

![image](https://user-images.githubusercontent.com/6818285/34456561-77faa6da-ed67-11e7-85fd-7d21660e00ad.png)

**Comment by cryptoeax** [comment]
Again, please use Google for general questions like this.

**Comment by ghost** [comment]
thanks, I found the solution and got it running but it would nice if this was included in the read.me so people dont have to do trial and error.

restarting the mysql server fixes it

sudo service mysql restart
