### ISSUE TITLE
Bot has stopped trading and went All-in

### ISSUE THREAD

**Issue by masoxik09** [cryptoeax/arbbot#60]
Hi, i have had an interesting error happening recently. 

The bot was running fine for over two weeks. Suddenly yesterday it bought pairs of stocks on both exchanges using all BTC. No error messages or alternating of settings during this period was present.

I tried to manually sell the currencies and restart the server and script (see the spike in screenshot), but the bot again did the same with different stocks keeping same amount of pairs on both exchanges. Last trade in P&L was yesterday 12:00 (see second screenshot)

Please advice  - should i reset the SQL database?

Thank you,
PR

![screen shot 2017-12-31 at 13 05 32](https://user-images.githubusercontent.com/34610968/34461586-2bd40d9c-ee2e-11e7-87c7-bae53348e8f1.png)
![screen shot 2017-12-31 at 13 27 55](https://user-images.githubusercontent.com/34610968/34461602-7c7639a0-ee2e-11e7-8c92-ab53b3f04862.png)

**Comment by masoxik09** [comment]
Dumping MySQL and reinstalling solved this issue. 

No errors was found, bot kept only buying and spending all available BTC until 0 while no sale orders for 3 days. Reinstalling solved it and now all works fine.

**Comment by cryptoeax** [comment]
Please consult the REAME file, the answer to why the bot has done this is written there.  It seems you haven't fully consulted the documentation, since the bot never buys altcoins until you tell it to.
