### ISSUE TITLE
/etc/init.d/nginx restart fail

### ISSUE THREAD

**Issue by ghost** [cryptoeax/arbbot#61]
Using the current webserver configuration recommended in the readme 
nginx restart is failing

the bot is running 
![image](https://user-images.githubusercontent.com/6818285/34469998-85144c64-eef6-11e7-94b7-51981c6dfe09.png)
however localhost is not working for the web configuration

sudo nginx -t showed there were no problems in configuration file
 
![image](https://user-images.githubusercontent.com/6818285/34470085-2547ecda-eef8-11e7-9405-4704cbe18b42.png)

error.log is empty

![image](https://user-images.githubusercontent.com/6818285/34470129-c7b99234-eef8-11e7-9a23-55a6132c94a3.png)

please advise of any suggestions

**Comment by ghost** [comment]
using sudo service nginx restart it showing OK instead of failed  but localhost is showing Apache 2 Ubuntu default page
![image](https://user-images.githubusercontent.com/6818285/34474183-949081b4-ef49-11e7-8979-23a8544f3638.png)

after changing listen 80 to listen [::]:80, localhost is showing the webinterface
server {

        listen [::]:80
        root /var/www/arbbot/web;
        index index.html;
        server_name localhost;

        location / {

                auth_basic           "Restricted area";
                auth_basic_user_file /var/www/conf/arbitrage.passwd;

        }

        location ~ \.php$ {

          include snippets/fastcgi-php.conf;
          fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;

        }

}

**Comment by cryptoeax** [comment]
Please stop filing nginx issues in this repository.  Thank you.
