### ISSUE TITLE
Bleutrade branch

### ISSUE THREAD

**Issue by remipaeta** [cryptoeax/arbbot#63]
Hello @cryptoeax,
There is always a http 525 or 522 error on Bleutrade when the bot refresh the wallets.
Do you know why ?

**Comment by cryptoeax** [comment]
Error 522: https://support.cloudflare.com/hc/en-us/articles/200171906
Error 525: https://support.cloudflare.com/hc/en-us/articles/200278659

Both indicate issues on Bleutrade's side.
