### ISSUE TITLE
failed buy orders on bittrex due to insufficient funds

### ISSUE THREAD

**Issue by Exalovic** [cryptoeax/arbbot#67]
I've been getting several of these errors after the commits on dec 30:
![6ch3zzq](https://user-images.githubusercontent.com/34724438/34539156-bbb2a628-f0cf-11e7-93a1-652c307afbc3.png)

It's very frustrating because it means I have to refund the coins again, leading to losses

**Comment by cryptoeax** [comment]
oops, it seems like the code has never taken the amount of funds available at the buy side into account!!!

https://github.com/cryptoeax/arbbot/blob/6318feb039122a6fc02ccaa824071811bea4b626/bot/Arbitrator.php#L281

**Comment by cryptoeax** [comment]
This fix was reverted in 9853a22aa15140986b6a106be8b4bf1c1776ff5c.

**Comment by cryptoeax** [comment]
I pushed a commit that I believe should have resolved a possible root cause of this.
