### ISSUE TITLE
The initial profitability calculation and the following checks have some kind of problem

### ISSUE THREAD

**Issue by Exalovic** [cryptoeax/arbbot#68]
I have been noticing that the bot has been making several trades that initially look like good profits, but end up giving a negative P&L when showing the final profit. 
This mostly happens with the coin DGB, but what ever is causing this could also be leading to the bot starting unprofitable trades with other coins

Notice the profit calculated first from the spread and the following profit calculations and the realized P&L 

![826yk4e](https://user-images.githubusercontent.com/34724438/34540577-5f49efd0-f0d5-11e7-83d7-54a36934edd5.png)

**Comment by cryptoeax** [comment]
I found this before you ;-)

Fixed by 4190bce29767410ae7d6e80d3a617f5f5c69e10f.
