### ISSUE TITLE
refreshWallets twice?

### ISSUE THREAD

**Issue by arvasko** [cryptoeax/arbbot#71]
At Arbitrator->loop(), there is a test condition to refresh wallets only if one hour (3600secs) has past. But then right below, outside the IF condition, there is a refreshWallets again. That makes wallets to be refreshed after 1 sec, right? Is it a bug?

**Comment by arvasko** [comment]
`private function loop() {

    Config::refresh();

    if ( time() > $this->nextCoinUpdate ) {
      if (!$this->walletsRefreshed) {
        $this->refreshWallets(); /* here is ok */
      }
      $this->refreshCoinPairs();
      $this->nextCoinUpdate = time() + 3600;
    }

    $this->refreshWallets(); /* again? isn`t this skipping the one hour condition?`

**Comment by cryptoeax** [comment]
The code you're complaining about is too old, it's already been removed in 66049a1b78d09666cfe40209f93052ad6a962f11.  (Please update regularly, this project is under active development!)
