### ISSUE TITLE
Can you add to config blocked exchanges

### ISSUE THREAD

**Issue by OlegVic** [cryptoeax/arbbot#74]
need add to main.php like this, will be good for block some exchanges without deleting files

```
foreach ( glob( 'bot/xchange/*.php' ) as $filename ) {
  $blocked = Config::get( Config::BLOCKED_EXCH, Config::DEFAULT_BLOCKED_EXCH );

  $name = basename( $filename, '.php' );
  if(strpos($blocked, $name) !== false){
      continue;
  }
  logg( "Enabling $name..." );
  require_once $filename;
  try {
    $exchanges[] = new $name;
  }
  catch ( Exception $ex ) {
    logg( "$name not configured" );
  }
}

```
and need some params in Config.php

**Comment by cryptoeax** [comment]
Well, the bot does support not enabling an exchange when the API key and/or secret for it isn't provided in the config file as is, without the need to provide a new config variable.  Based on the code snippet you have provided above, the flag you're asking for would have the exact same effect, so I think the existing support should be sufficient for your needs.  If you need more specific customizations please feel free to reopen.
