### ISSUE TITLE
The bot sometimes overbuys when oversell protection is on

### ISSUE THREAD

**Issue by Exalovic** [cryptoeax/arbbot#80]
As seen the bot placed a buy order for 627 but actually bought 827
![hw3ote9](https://user-images.githubusercontent.com/34724438/34705863-c9a9d2e6-f503-11e7-8b0d-0ec350c501c6.png)

**Comment by crypto-maniac** [comment]
any update on this please?
thx

**Comment by cryptoeax** [comment]
> any update on this please?

This is a volunteer project.  If there is nothing posted here it means there's no updates.  I'm aware of the issue and have been working on other things.

**Comment by crypto-maniac** [comment]
of course no problem , i have no problem to send you money soon the bot make me money :)

**Comment by cryptoeax** [comment]
That will be appreciated and will definitely help incentivize further development.  The donation addresses can be found in the README.  :-)

**Comment by cryptoeax** [comment]
I have pushed an important fix that I believe should have improved this situation now (9001055a23ef921aea41cc00b307d4c1cbb7e3b9).  Please reopen if you see this again after that fix.
