### ISSUE TITLE
The bot does throws an error when a currency goes offline

### ISSUE THREAD

**Issue by Exalovic** [cryptoeax/arbbot#83]
As seen here siacoin wallet is offline on bittrex and the bot gets an error
![rv0d4ko](https://user-images.githubusercontent.com/34724438/34780292-099112f0-f623-11e7-9760-14262a6c4f7f.png)

**Comment by heiko7even** [comment]
Error if wallet is offline :(

<img width="1305" alt="bildschirmfoto 2018-01-11 um 14 06 09" src="https://user-images.githubusercontent.com/27195613/34826914-ba1c55d4-f6d8-11e7-975f-782a57243d1c.png">

**Comment by cryptoeax** [comment]
> Error if wallet is offline :(

I'm not sure if you've understood the point of the previous commit...  Its point is to make sure the currency isn't used again once you get this error.

**Comment by cryptoeax** [comment]
985ee88 makes us not attempt to retry when we get this error but that's more of a cosmetic change.
