### ISSUE TITLE
Order execution timeout during liquidation on poloniex

### ISSUE THREAD

**Issue by Exalovic** [cryptoeax/arbbot#93]
Got this error while running the liquidation module, the bot did nothing for several minutes following this

![ytiogl6](https://user-images.githubusercontent.com/34724438/34884673-b6328eee-f7bd-11e7-99af-755156c53c42.png)

**Comment by cryptoeax** [comment]
The wait after this was just caused because the bot was sleeping in between jobs, nothing to be alarmed about.  I reduced the channel timeouts to 10s in ae77252.
