### ISSUE TITLE
ERROR during management task: API error response: ADDRESS_GENERATING

### ISSUE THREAD

**Issue by heiko7even** [cryptoeax/arbbot#94]
Got this error during management Task

<img width="1292" alt="bildschirmfoto 2018-01-13 um 16 02 18" src="https://user-images.githubusercontent.com/27195613/34907201-2f1984b2-f87b-11e7-8eb8-a5eb74e988a3.png">

**Comment by ghost** [comment]
Did you end up ever finding a resolution?  I am getting the same error
