### ISSUE TITLE
Undersell protection leads to a buy order with too low quantity

### ISSUE THREAD

**Issue by andygoossens** [cryptoeax/arbbot#95]
I have turned on undersell protection to avoid frequent losses between Bluetrade and HitBTC (OlegVic's implementation; Poloniex and Bittrex aren't an option for me ATM).

So what happened: a sell order was placed on Bleutrade. We waited for a fraction (*= 0.1) of the regular wait time but the order was still not completely fulfilled. Arbbot then tries to place a sell order but HitBTC refused that with the "Quantity too low" reason.

I think we can avoid sending the buy order if we notice that its quantity is too low.

Log:
```
18:36:52: Placed sell order (BLEUTRADE ID: 12345678)
18:36:52: Waiting for order execution...
18:37:00: A sell order hasn't been filled. If this happens regulary you should increase the expert.order-check-delay setting!
18:37:09: Received 539.824979 DOGE from the exchange while waiting for a trade of 11368.300026
18:37:09: Warning: Meant to sell 11368.30002622 but managed to only sell 539.82497949
18:37:10: [HITBTC] API error response: Code [2011] Quantity too low
18:37:10: [HITBTC] API error response: Code [2011] Quantity too low
18:37:10: [HITBTC] API error response: Code [2011] Quantity too low
18:37:10: [HITBTC] API error response: Code [2011] Quantity too low
18:37:10: [HITBTC] API error response: Code [2011] Quantity too low
18:37:10: [HITBTC] Got an exception in buy(): API error response: Code [2011] Quantity too low
18:37:10: Buy order failed, we will probably incur a profit (but we have really sold off our altcoin), so let's retry...
18:37:11: [HITBTC] API error response: Code [2011] Quantity too low
...
```

**Comment by cryptoeax** [comment]
This is a bug in @OlegVic's code: https://github.com/OlegVic/arbbot_exchanges/blob/d5bc7f0021fef827c48f99a78eb3084058f74543/Hitbtc.php#L448

According to https://hitbtc.com/faq/trading, the minimum order size there is 0.01BTC but the bot incorrectly thinks it can place 0.001 order sizes.

FWIW I haven't yet tested that exchange, and exchange implementations can have all sorts of bugs that can cause the bot to function incorrectly, as you can see... :-)

**Comment by cryptoeax** [comment]
Submitted a fix there: https://github.com/OlegVic/arbbot_exchanges/pull/1

**Comment by andygoossens** [comment]
My first thought was to blame the Hitbtc implementation as well. But then I noticed that the bot never checked whether the new buy order size (after undersell corrections) was big enough. You could have this issue with any other exchange.

**Comment by cryptoeax** [comment]
Yes, now I see that you are right, we are missing a check here.  I stopped looking further when I noticed the HitBTC bug, my apologies...

**Comment by cryptoeax** [comment]
Fixed on the binance branch.
