### ISSUE TITLE
Stop sending logs to MySQL

### ISSUE THREAD

**Issue by claytondukes** [cryptoeax/arbbot#96]
You should really work on another method for logging - sending to MySql will severely degrade OS performance in this case because many people are using smaller $5 cloud instances with very little ram. when the OS runs out of ram, it will use swap which slaughter's performance. 

The end result is that querying the DB while inserting will most likely cause trade issues (just a guess, but after 48 hours, I am already seeing problems with the OS.

**Comment by andygoossens** [comment]
There is a job to clean up the log table.

It seems that the first cleanup will happen after 7 days, and from then on it will adhere to the configuration parameter ("interval-db-cleanup" in the [expert] section). Which is set to 24 hours at the moment.

Each time it runs it will clean up log rows older than "max-log-age" hours.

If you want to run it immediately (well, after the bot has finished his ongoing task), execute this SQL statement:
`update stats set value=0 where keyy='next_db_cleanup';`

**Comment by andygoossens** [comment]
Oh, and if you change the "interval-db-cleanup" value, then it will only come into effect after the next run.

**Comment by claytondukes** [comment]
fwiw, this happened just now:

```
Mon Jan 15 06:26:07 2018] Out of memory: Kill process 7453 (mysqld) score 413 or sacrifice child
[Mon Jan 15 06:26:07 2018] Killed process 7453 (mysqld) total-vm:1121564kB, anon-rss:206028kB, file-rss:0kB
```

**Comment by cryptoeax** [comment]
I agree that sending logs to mysql isn't ideal.  I'm hoping to change this after moving the bot to docker.  Any help is appreciated.  :-)

**Comment by sigismund** [comment]
Regarding docker, you already have pull request waiting for you.
So you were thinking adding option of sending logs to mongodb or something like that?

**Comment by logzilla** [comment]
My .02:
Just log to syslog and let the end user decide from there.

I'd suggest not having the app log to any DB, that's extra overhead on the server when a lot of people are only using $5/mo instances - and, if disk I/O becomes starved, that may slow down the bot.

**Comment by cryptoeax** [comment]
> Regarding docker, you already have pull request waiting for you.

I already have a half-working dockerization branch but I have started incorporating parts of your PR using the command line tools.  Github only lets you do whole-sale merges unfortunately which is why the PR is sitting dormant, but I'm actively using it.  :-)

> So you were thinking adding option of sending logs to mongodb or something like that?

"something like that..."  But I tend to agree with @logzilla that the best route is probably logging to syslog.  It seems that docker provides some decent facilities for pulling logs out of a container: https://docs.docker.com/engine/admin/logging/overview/#supported-logging-drivers

**Comment by cryptoeax** [comment]
Closing this in favor of #105.
